In [2]:
import pandas as pd

In [3]:
import musical
import numpy as np
import pickle
import logging
import pandas as pd
import argparse
import sys
import os
sys.path.append('../src/utils/')
from sorted_array import SORTED_CAT_ARRAY
from sorted_array import SORTED_CAT_ARRAY_RT

In [4]:
#used for the paper
features = 'RFD'
#features = 'repliTiming_mp' # replication timing at midpoint

In [20]:
matrix_folder = '../data/processed/SVmatrices/PCAWG/'

In [21]:
breast_fn = matrix_folder+features+'/Breast_'+features+'.csv'
breast_cat = pd.read_csv(breast_fn, index_col=0)

In [6]:
breast_cat.head(1)

,clustered_del_1-10Kb_L_L,clustered_del_1-10Kb_L_R,clustered_del_1-10Kb_R_L,clustered_del_1-10Kb_R_R,clustered_del_10-100Kb_L_L,clustered_del_10-100Kb_L_R,clustered_del_10-100Kb_R_L,clustered_del_10-100Kb_R_R,clustered_del_100Kb-1Mb_L_L,clustered_del_100Kb-1Mb_L_R,...,non-clustered_inv_1Mb-10Mb_R_L,non-clustered_inv_1Mb-10Mb_R_R,non-clustered_inv_>10Mb_L_L,non-clustered_inv_>10Mb_L_R,non-clustered_inv_>10Mb_R_L,non-clustered_inv_>10Mb_R_R,non-clustered_trans_L_L,non-clustered_trans_L_R,non-clustered_trans_R_L,non-clustered_trans_R_R
f39cc911-36a7-4c06-9e91-4ad86281db3d,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [7]:
ovary_fn = matrix_folder+features+'/Ovary_'+features+'.csv'
ovary_cat = pd.read_csv(ovary_fn, index_col=0)

In [8]:
prostate_fn = matrix_folder+features+'/Prostate_'+features+'.csv'
prostate_cat = pd.read_csv(prostate_fn, index_col=0)

In [9]:
esophagus_fn = matrix_folder+features+'/Esophagus_'+features+'.csv'
esophagus_cat = pd.read_csv(esophagus_fn, index_col=0)

In [10]:
lung_fn = matrix_folder+features+'/Lung_'+features+'.csv'
lung_cat = pd.read_csv(lung_fn, index_col=0)

In [11]:
sel_pantissue_rfd_cat = pd.concat([breast_cat, ovary_cat, prostate_cat, esophagus_cat, lung_cat]).T

In [12]:
breast_cat.shape

(187, 128)

In [13]:
breast_cat.head(1)

,clustered_del_1-10Kb_L_L,clustered_del_1-10Kb_L_R,clustered_del_1-10Kb_R_L,clustered_del_1-10Kb_R_R,clustered_del_10-100Kb_L_L,clustered_del_10-100Kb_L_R,clustered_del_10-100Kb_R_L,clustered_del_10-100Kb_R_R,clustered_del_100Kb-1Mb_L_L,clustered_del_100Kb-1Mb_L_R,...,non-clustered_inv_1Mb-10Mb_R_L,non-clustered_inv_1Mb-10Mb_R_R,non-clustered_inv_>10Mb_L_L,non-clustered_inv_>10Mb_L_R,non-clustered_inv_>10Mb_R_L,non-clustered_inv_>10Mb_R_R,non-clustered_trans_L_L,non-clustered_trans_L_R,non-clustered_trans_R_L,non-clustered_trans_R_R
f39cc911-36a7-4c06-9e91-4ad86281db3d,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [14]:
sel_pantissue_rfd_cat.head(1)

,f39cc911-36a7-4c06-9e91-4ad86281db3d,e7dc7492-3a84-49c7-8dea-8f508b53dc40,8f558713-f32b-403b-aedf-c79efeb41c67,1eb62abc-7928-405b-84cc-f091ca5347b2,f9f04e42-63a2-4ee1-ade4-9e5bb5c20cdd,ec4d4cbc-d5d1-418d-a292-cad9576624fd,01658141-8398-4585-9f0f-8355dd9b0604,fc6d77a9-121b-48ab-a899-713c3d1319a2,07b5141f-ac79-439b-883b-b0183bbe7ff5,7b0b60c7-5fa0-440e-937f-8d82119330d6,...,706868b5-4920-433a-bea3-92e9bf83059b,b7a7d93b-38a7-4fc3-a433-3bb0a8cb7c42,2fe2433b-9a55-431f-a869-2b5a63e8e8fc,84e601b7-dfa5-4cd5-9fef-07f03967a0d4,9623d295-c23d-4f2f-827c-69f767a26f1f,b88f014e-bc0f-4775-8228-39e0b471c3b0,24badf07-8615-48a3-8d6e-45c3d783f18d,7ac0b303-d685-4fa5-bfec-34d2ba1dbc8e,ad41f1f3-e38e-4418-9c16-52bca5719f39,48f68f73-3ac0-44ac-ba12-b8889fcb7f38
clustered_del_1-10Kb_L_L,0,0,0,0,1,2,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [15]:
sel_pantissue_rfd_cat.index.name = 'Mutation type'
sel_pantissue_rfd_cat.to_csv(matrix_folder+features+'/Selected_'+features+'.csv')