In [19]:
import pandas as pd

In [78]:
#rt_cat = pd.read_csv('/home/dg204/projects/rsignatures/data/processed/SVmatrices/GEL/all_tissue_cat_repliTiming_mp.csv')
rt_cat = pd.read_csv('/home/dg204/projects/rsignatures/data/processed/SVmatrices/GEL/sel_tissue_cat_repliTiming_mp.csv', index_col=0)

In [79]:
rt_cat.shape

(4948, 160)

In [80]:
rt_cat.head()

,clustered_del_>10Mb_very late,clustered_del_1-10Kb_very late,clustered_del_10-100Kb_very late,clustered_del_100Kb-1Mb_very late,clustered_del_1Mb-10Mb_very late,clustered_inv_>10Mb_very late,clustered_inv_1-10Kb_very late,clustered_inv_10-100Kb_very late,clustered_inv_100Kb-1Mb_very late,clustered_inv_1Mb-10Mb_very late,...,non-clustered_inv_1-10Kb_very early,non-clustered_inv_10-100Kb_very early,non-clustered_inv_100Kb-1Mb_very early,non-clustered_inv_1Mb-10Mb_very early,non-clustered_tds_>10Mb_very early,non-clustered_tds_1-10Kb_very early,non-clustered_tds_10-100Kb_very early,non-clustered_tds_100Kb-1Mb_very early,non-clustered_tds_1Mb-10Mb_very early,non-clustered_trans_very early
0,6,1,1,0,3,15,1,0,0,10,...,0,0,0,0,1,0,1,0,1,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,2,0,0,0,0,...,3,0,1,3,1,1,0,0,1,1
4,0,0,0,1,0,1,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0

In [81]:
rt_cat.values.sum()

np.int64(430517)

In [82]:
#rfd_cat = pd.read_csv('/home/dg204/projects/rsignatures/data/processed/SVmatrices/GEL/all_tissue_cat_RFD.csv')
rfd_cat = pd.read_csv('/home/dg204/projects/rsignatures/data/processed/SVmatrices/GEL/sel_tissue_cat_RFD.csv', index_col=0)

In [83]:
rfd_cat.shape

(4948, 128)

In [84]:
rfd_cat.values.sum()

np.int64(422710)

In [67]:
pcawg_rt_cat = pd.read_csv('/home/dg204/projects/rsignatures/data/processed/SVmatrices/PCAWG/repliTiming_mp/Selected_repliTiming_mp.csv', index_col=0).T
colnames_sel = [c for c in pcawg_rt_cat.columns if 'non-clustered' in c]
pcawg_rt_cat = pcawg_rt_cat.loc[:,colnames_sel]

In [68]:
pcawg_rt_cat.shape

(631, 80)

In [70]:
pcawg_rt_cat.values.sum()

np.int64(89037)

In [71]:
pcawg_rt_cat.head(1)

Mutation type,non-clustered_del_1-10Kb_very early,non-clustered_del_1-10Kb_early,non-clustered_del_1-10Kb_medium,non-clustered_del_1-10Kb_late,non-clustered_del_1-10Kb_very late,non-clustered_del_10-100Kb_very early,non-clustered_del_10-100Kb_early,non-clustered_del_10-100Kb_medium,non-clustered_del_10-100Kb_late,non-clustered_del_10-100Kb_very late,...,non-clustered_inv_>10Mb_very early,non-clustered_inv_>10Mb_early,non-clustered_inv_>10Mb_medium,non-clustered_inv_>10Mb_late,non-clustered_inv_>10Mb_very late,non-clustered_trans_very early,non-clustered_trans_early,non-clustered_trans_medium,non-clustered_trans_late,non-clustered_trans_very late
f39cc911-36a7-4c06-9e91-4ad86281db3d,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [72]:
pcawg_rfd_cat = pd.read_csv('/home/dg204/projects/rsignatures/data/processed/SVmatrices/PCAWG/RFD/Selected_RFD.csv', index_col=0).T
colnames_sel = [c for c in pcawg_rfd_cat.columns if 'non-clustered' in c]
pcawg_rfd_cat = pcawg_rfd_cat.loc[:,colnames_sel]

In [73]:
pcawg_rfd_cat.shape

(631, 64)

In [74]:
pcawg_rfd_cat.values.sum()

np.int64(88784)

In [75]:
pcawg_rfd_cat.head()

Mutation type,non-clustered_del_1-10Kb_L_L,non-clustered_del_1-10Kb_L_R,non-clustered_del_1-10Kb_R_L,non-clustered_del_1-10Kb_R_R,non-clustered_del_10-100Kb_L_L,non-clustered_del_10-100Kb_L_R,non-clustered_del_10-100Kb_R_L,non-clustered_del_10-100Kb_R_R,non-clustered_del_100Kb-1Mb_L_L,non-clustered_del_100Kb-1Mb_L_R,...,non-clustered_inv_1Mb-10Mb_R_L,non-clustered_inv_1Mb-10Mb_R_R,non-clustered_inv_>10Mb_L_L,non-clustered_inv_>10Mb_L_R,non-clustered_inv_>10Mb_R_L,non-clustered_inv_>10Mb_R_R,non-clustered_trans_L_L,non-clustered_trans_L_R,non-clustered_trans_R_L,non-clustered_trans_R_R
f39cc911-36a7-4c06-9e91-4ad86281db3d,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
e7dc7492-3a84-49c7-8dea-8f508b53dc40,3,0,0,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
8f558713-f32b-403b-aedf-c79efeb41c67,1,0,0,1,3,0,1,2,0,1,...,0,4,1,3,4,1,8,7,6,7
1eb62abc-7928-405b-84cc-f091ca5347b2,3,0,2,6,2,1,1,3,1,1,...,4,0,0,1,1,1,2,2,1,2
f9f04e42-63a2-4ee1-ade4-9e5bb5c20cdd,0,0,0,0,1,2,0,0,0,1,...,0,3,0,0,0,0,0,0,0,0